<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "instagramapi"
 *
 * Auto generated by Extension Builder 2020-09-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'instagram_api',
    'description' => 'This extension let you to create gallery instagram and refresh the api Key by a scheduler task you can planified',
    'category' => 'plugin',
    'author' => 'Taieb.rekik',
    'author_email' => 'taieb20001@gmail.com',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-10.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
